name: starmind
description: StarMind - Offline AI Assistant
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  go_router: ^14.2.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  yandex_auth_sdk: ^1.4.0
  flutter_secure_storage: ^9.2.2
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  speech_to_text: ^6.6.0
  file_picker: ^8.1.2
  device_calendar: ^4.3.1
  flutter_local_notifications: ^17.1.2
  alarm: ^3.0.5
  timezone: ^0.9.2
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  shared_preferences: ^2.3.1
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.3.4
  crypto: ^3.0.3
  intl: ^0.19.0
  uuid: ^4.4.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/phi35mini_quant.tflite
    - assets/models/tokenizer.json
    - assets/faiss/index.bin
    - assets/prompts/
    - assets/games/
